### ISSUE TITLE
Integrate cab controls with Loco Lights Mod

### ISSUE THREAD

**Issue by katycat5e** [katycat5e/DVCustomCarLoader#10]

**Comment by fauxnik** [comment]
Interested to learn what would be involved here, and if I can help. Let me know! 🙂

**Comment by katycat5e** [comment]
With the updates to the cab input handling, it's unclear if direct integration with loco lights would be necessary, since that mod deals with existing locos, and custom locos could be equipped with working lights via CCL scripts. Perhaps a new type of indicator component that uses a light as its output, this can then be hooked to cab controls using the existing CCL event system.

**Comment by katycat5e** [comment]
Shouldn't be any compatibility issues going forward. CCL now has native headlight components & controls.
