### ISSUE TITLE
Emission Indicators clamped to 1 intensity

### ISSUE THREAD

**Issue by GregTame** [katycat5e/DVCustomCarLoader#119]
Emission indicators (for both lights and material emission) is clamped to 1 intensity. 

Repro: 

1. Create an emission indicator, 
2. set the Max Emission to like, 1000 and bind it to the throttle
3. load ingame and up the throttle, 

expected: Emission intensity should scale all the way up to the set intensity

results: Emission intensity scales between 0 and 1, instead of hitting 1 at 0.1%.

**Comment by katycat5e** [comment]
TODO: patch IndicatorEmission.OnValueSet, lerp emissionColor between minEmission/maxEmission
