### ISSUE TITLE
Steam locos do not produce chuffing sound in reverse

### ISSUE THREAD

**Issue by GregTame** [katycat5e/DVCustomCarLoader#44]
**Describe the bug**
Title says it all, steam locos make no noise going backwards.

**To Reproduce**
1. Make a steam engine, including sounds setup
2. Load it in game
3. Drive it backwards

**Expected behavior**
The locomotive to make a chuffing sound

**Actual behavior**
The locomotive silently moves backwards

video:
https://youtu.be/Y9N3ChC5aVQ

**Comment by katycat5e** [comment]
Investigate - [CustomChuffController absolute value wheel speed?](https://github.com/katycat5e/DVCustomCarLoader/blob/d03aa06a7f14cc7b6883454985d43cb2281af486/DVCustomCarLoader/LocoComponents/Steam/CustomChuffController.cs#L49)
