### ISSUE TITLE
Ability to adjust water/steam consumption rates

### ISSUE THREAD

**Issue by GregTame** [katycat5e/DVCustomCarLoader#49]
Pretty straight forward. it would be very handy if you could adjust how much steam your locomotive uses.

why? different sized locos consume different amounts of steam.

**Comment by katycat5e** [comment]
[STEAM_PIPE_MULT](https://github.com/katycat5e/DVCustomCarLoader/blob/d03aa06a7f14cc7b6883454985d43cb2281af486/DVCustomCarLoader/LocoComponents/Steam/CustomLocoSimSteam.cs#L355)
[POWER_MULT](https://github.com/katycat5e/DVCustomCarLoader/blob/d03aa06a7f14cc7b6883454985d43cb2281af486/DVCustomCarLoader/LocoComponents/Steam/CustomLocoSimSteam.cs#L362)
Convert to SimParams fields

**Comment by katycat5e** [comment]
Closed by #53
